### ISSUE TITLE
Confluence Migrator missing labels.json , attachements.json, hierarchy.json  

### ISSUE THREAD

**Issue by venkymiel623** [solidify/atlassian-migration-suite-docs#1]
Hi @Alexander-Hjelm ,

**While doing confluence migration step.2 while run the command we are getting below error files not found** 

No proper guidance how to generate below json files 
kindly help me on this 

2024-07-30 15:21:25,201 : ERROR : Error deleting the file './hierarchy.json': [WinError 2] The system cannot find the file specified: './hierarchy.json'
2024-07-30 15:21:25,217 : ERROR : Error deleting the file './labels.json': [WinError 2] The system cannot find the file specified: './labels.json'  
2024-07-30 15:21:25,217 : ERROR : Error deleting the file './issue_wi_map.json': [WinError 2] The system cannot find the file specified: './issue_wi_map.json'
2024-07-30 15:21:25,217 : ERROR : Error deleting the file './attachment_map.json': [WinError 2] The system cannot find the file specified: './attachment_map.json'
Traceback (most recent call last):
  File "requests\models.py", line 974, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Alexander-Hjelm** [comment]
Hello @venkymiel623.

Please email us at [support.jira-migrator@solidify.dev](mailto:support.jira-migrator@solidify.dev) and do not use this issue board. :)

We will de what we can to assist you over email!
